name: Rails tests
on: [push]
jobs:
  rubocop-checker:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install Rubocop
        run: gem install rubocop
      - name: Check code
        run: rubocop